export const Users = [
  {
    id:1,
    profilePicture: "/profile/amira.jpg",
    username: "Amira Tamzini",
  },
  {
    id:2,
    profilePicture: "/profile/fakhri.jpg",
    username: "Fakhri Zitouni",
  },
  {
    id:3,
    profilePicture: "/profile/hedi.jpg",
    username: "Hedi Loumi",
  },
  {
    id:4,
    profilePicture: "/profile/lamia.jpg",
    username: "Lamia Ben Salah",
  },
  {
    id:5,
    profilePicture: "/profile/said.jpg",
    username: "Said Ben Mbarek",
  },
  {
    id:6,
    profilePicture: "/profile/salah.jpg",
    username: "Salah Zribi",
  },
  {
    id:7,
    profilePicture: "/profile/salma.jpg",
    username: "Salma Gharbi",
  },
  {
    id:8,
    profilePicture: "/profile/sami.jpg",
    username: "Sami Ben Amor",
  },
  {
    id:9,
    profilePicture: "/profile/samira1.jpg",
    username: "Samira Mahmoud",
  },
  {
    id:10,
    profilePicture: "/profile/soumaya1.jpg",
    username: "Soumaya Selmi",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "covid-19",
    photo: "/posts/c19.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "/posts/covid test.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "experience is always the answer",
    photo: "/posts/test.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "/posts/sc.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "/posts/vaccin.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "/posts/delta.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "science is the key.",
    photo: "/posts/lab.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "/posts/download.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by working hard.",
    photo: "/posts/lab1.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "/posts/virus.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
